name: Pull from upstream daily

on:
  schedule:
    - cron: "0 20 * * *" # 4:00 AM UTC+8
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sing-box-rules:
    name: Update sing-box-rules
    runs-on: ubuntu-latest
    steps:
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch master
      - name: Update rules
        run: |
          git clone --branch sing https://github.com/MetaCubeX/meta-rules-dat.git
          cd meta-rules-dat/geo/
          curl -fsSLo downloader.srs https://raw.githubusercontent.com/senzyo/sing-box-rules/master/downloader.srs
          curl -fsSLo downloader.json https://raw.githubusercontent.com/senzyo/sing-box-rules/master/downloader.json
          git init
          git add -A
          git commit -m "更新于 $(date +'%Y-%m-%d %H:%M:%S') (UTC+0)"
          git remote add origin https://${{ secrets.PERSONAL_TOKEN }}@github.com/senzyo/sing-box-rules.git
          git push -uf origin master:master
